import "../global.css";

import Head from "next/head";

import Header from "../Components/Header/Header";
import Footer from "../Components/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Geo</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
