import "./Global.css";
import UnAuthHeader from "@/Components/UnAuthHeader/UnAuthHeader";
import UnAuthFooter from "@/Components/UnAuthFooter/UnAuthFooter";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UnAuthHeader />
        {children}
        <UnAuthFooter />
        <footer>footer</footer>
      </body>
    </html>
  );
}
