import "./Global.css";

import AuthWrapper from "@/Components/AuthWrapper/AuthWrapper";
import UnAuthHeader from "@/Components/UnAuthHeader/UnAuthHeader";
import UnAuthFooter from "@/Components/UnAuthFooter/UnAuthFooter";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthWrapper>
          <UnAuthHeader />
          {children}
          <UnAuthFooter />
        </AuthWrapper>
      </body>
    </html>
  );
}
